<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	  <UserSecretsId>dbe3eaee-afb9-4fe1-a6e6-e5318990fd30</UserSecretsId>
  </PropertyGroup>
	<ItemGroup>
		<Using Include="System.Console" Static="true" />
		<!--<Using Remove="System.Linq" />-->
	</ItemGroup>
	
</Project>
